# Generated by Django 5.2.11 on 2026-03-01 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('source', models.CharField(max_length=100)),
                ('published_date', models.DateTimeField()),
                ('related_tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_articles', to='tools.tool')),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
    ]
